// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTqrhmUg57ElHD2_6tCyesLotqtnNl_FI',
    appId: '1:324307634567:web:0fd486dcc63a7b3e22ab22',
    messagingSenderId: '324307634567',
    projectId: 'ecom-945b2',
    authDomain: 'ecom-945b2.firebaseapp.com',
    storageBucket: 'ecom-945b2.appspot.com',
    measurementId: 'G-TS4EFEHMEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDATU3lPYiVk02RlXg1cu3SzVDb1cNwy7g',
    appId: '1:324307634567:android:32b1523decc97cd022ab22',
    messagingSenderId: '324307634567',
    projectId: 'ecom-945b2',
    storageBucket: 'ecom-945b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiZzwnG7Oi2VIEkjMX8TUpY224Ff34tNM',
    appId: '1:324307634567:ios:bc26ce94817d99f722ab22',
    messagingSenderId: '324307634567',
    projectId: 'ecom-945b2',
    storageBucket: 'ecom-945b2.appspot.com',
    androidClientId: '324307634567-25ka2100r0ui8c5l4e3h3mc76v8c66rp.apps.googleusercontent.com',
    iosClientId: '324307634567-g19ns9uvin1rjpgshefhnn3hqug52a33.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiZzwnG7Oi2VIEkjMX8TUpY224Ff34tNM',
    appId: '1:324307634567:ios:bc26ce94817d99f722ab22',
    messagingSenderId: '324307634567',
    projectId: 'ecom-945b2',
    storageBucket: 'ecom-945b2.appspot.com',
    androidClientId: '324307634567-25ka2100r0ui8c5l4e3h3mc76v8c66rp.apps.googleusercontent.com',
    iosClientId: '324307634567-g19ns9uvin1rjpgshefhnn3hqug52a33.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );
}
